### PR TITLE
upgraded mubsub to support mongo 3

### PR DESCRIPTION
**Pull request by yawetse**

### CODE REVIEW

**Comment by exilonX** [comment]
This issue (https://github.com/modit/socket.io-adapter-mongo/issues/8) is linked to this pull request.

**Comment by shannonmpoole** [comment]
I've merged this in but the tests are no longer passing. It seems like they aren't passing anymore for the commit before this pull request either so I need to dig deeper into this when I have a chance. Once I sort it out I will release it on npm.

**Comment by yawetse** [comment]
thanks @shannonmpoole I appreciate that!

**Comment by shannonmpoole** [comment]
I've updated the tests to match the original socket.io-redis module and they are passing now. I haven't been in this code base in a while and I have to trust that they have a better handle on the tests than I do. Their new tests look simpler and more to the point.

Anyways, released as 0.1.5 on npm. Thanks for contributing!

**Pull request merged**
