### PR TITLE
Added support for multiple hosts and replica set

### PR DESCRIPTION
**Pull request by supericeboy**

### CODE REVIEW

**Comment by lklepner** [comment]
This will be helpful for my project. Thanks for the PR supericeboy

**Review by lklepner — APPROVED** [review]
Looking good on my end

**Comment by lklepner** [comment]
Any word on merging this PR? It would be great to get replica set support in place.

**Comment by lklepner** [comment]
One use case this PR does not address is support for replica sets via the URI. As the code stands the connection string URI is reduced down to a single host/port combination prior to being passed through to mubsub. Its unclear to me what the purpose/advantage of this might be.

**Comment by shannon** [comment]
@lklepner sorry it's been a long time since I've looked at this code base. This could probably use a new owner if anyone is interested. Modit it longer in business so I doubt they will be maintaining it. 

But looking at this I think multiple hosts could just be passed in the URI (the first argument) which gets parsed by https://github.com/mongolab/mongodb-uri-node.

The host and port options were really just for convenience. I wouldn't expect it to meet everyone's use case. I think using the standard Mongo URI is the way to go for these other use cases.

**Comment by shannon** [comment]
Sorry looking at this more I see it's parsing the URI but it's only pulling out the first host and port. So I think an alternative to this PR would be to make it so it can just use the URI as is. Which would cover a lot more use cases.

**Comment by shannon** [comment]
@lklepner came to the same conclusion apparently :-)

**Comment by lklepner** [comment]
@shannon Thanks for the background info. 

URI passthrough seems like a win to me. I made this change in an internal repo but would be happy to clean it up a bit (eliminating the code which currently rebuilds the URI) and submit a PR. 

I could also see doing a semantic version bump to 1.x (to reduce user disruption) and eliminating the object based configuration entirely (host/port/db/username/password specification) in favor of a URI-only setup in the interest of streamlining / future-proofing.

If a new maintainer is desired I'd be happy to step up. I'm actively using the project for a while so it seems fitting that I step up if needed.

**Comment by shannon** [comment]
@lklepner That sounds like the right approach. 

I've never passed ownership of a module but I guess the first step would be to just add you as a collaborator in npm. Do you have an npm account? You could just publish your fork when you are ready and we could add an unmaintained message to this repo and link to yours.

My concern about leaving it in the modit account and adding you as a collaborator here is I don't think there's anyone there that even knows this is here. They may just delete the GitHub account for inactivity at some point.

**Comment by lklepner** [comment]
@shannon That approach works. I sent npmjs support an email (with you CC'd) outlining the situation to get their input, if any.

I'm happy to proceed in the way you've outlined if we don't hear back

**Comment by lklepner** [comment]
@shannon NPM has transferred ownership of the socket.io-adapter-mongo module to me and I have published an update with a semantic version bump that addresses the issue(s) we discussed above.

**Comment by shannon** [comment]
@lklepner I have updated the readme indicating that this has repo has been deprecated and all issues and pull requests should be directed to yours.

I'm going to close out the existing issues and PRs here.

**Pull request closed without merging**
